openapi: 3.0.0
info:
  title: Flight Check-In API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /check-in/boarding-pass:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
    parameters: []
  '/check-in/{flightNumber}/{ticketNumber}':
    post:
      summary: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../common/models/flight.v1.yaml
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                passportNumber:
                  type: string
    parameters:
      - schema:
          type: string
          pattern: '^[A-Z]{2}[0-9]{4}$'
        name: flightNumber
        in: path
        required: true
      - schema:
          type: string
        name: ticketNumber
        in: path
        required: true
  '/check-in/passengers/{flightNumber}/{ticketNumber}':
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  flights:
                    type: array
                    items:
                      $ref: ../common/models/flight.v1.yaml
      parameters: []
    parameters:
      - schema:
          type: string
          pattern: '^[A-Z]+ [0-9]+$'
        name: flightNumber
        in: path
        required: true
      - schema:
          type: number
        name: ticketNumber
        in: path
        required: true
components:
  schemas: {}
