openapi: 3.0.0
info:
  title: Flight Check-In Step 1
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /check-in/passengers:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {} 